### ISSUE TITLE
Drop HHVM testing

### ISSUE THREAD

**Issue by matthewtrask** [phergie/phergie-irc-client-react#61]
With the advent of 7.0, HHVM has fallen to the way side. An ancedote from LonestarPHP shows that no one (within reason) is using HHVM, so I wanted to get feedback about removing it from CI testing. 

cc @elazar @WyriHaximus @elstamey @svpernova09

**Comment by svpernova09** [comment]
We just dropped HHVM from Laravel Homestead since the Laravel Framework itself has dropped support for HHVM. I’m fine dropping HHVM support from Phergie.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by WyriHaximus** [comment]
Fine by me, haven't heard anyone requesting HHVM support in ages for packages tbh.

**Comment by elazar** [comment]
I can say that my employer is currently in the process of moving away from HHVM to PHP 7. I'd be fine with dropping HHVM support. Here are some related commits involving code we may be able to clean up or otherwise modify if HHVM support is removed:

9da63711bc43e41e995a3c565f21cb4129374502
a317d165220f9caa3937217399c2b4a3c71033fa
17a9fb43bd3595762268faa8b7025b36b56c862a
7e08ed4939e89b3fef7f5599687b2338767ca7bb
